spring:
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
    discovery-client-enabled: false
  #采样取值介于 0到1之间，1则表示全部收集
  sleuth:
    sampler:
      probability: 1
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tQadfgRREhGS42psboD
      secret-key:  OOD87THJWMNN7GF5Q679Y8M
      oss:
        bucket: guilimall-fjc
        endpoint: oss-cn-shanghai.aliyuncs.com
      # 发送短信接口的配置
      sms:
        host: http://dingxin.market.alicloudapi.com
        path: /data/send_sms
        appcode: 72a370aeccf34090aa7254ab040f1f0
    sentinel:
      transport:
        dashboard: localhost:8080

  application:
    name: gulimall-third-party

server:
  port: 30000


management:
  endpoints:
    web:
      exposure:
        include: '*'
